// CRITICAL: must be first — patches LitElement before any component is loaded.
import '@lit-labs/ssr-client/lit-element-hydrate-support.js';

// Client runtime: router outlet and link custom elements.
import '@beatzball/litro/runtime/LitroOutlet.js';
import '@beatzball/litro/runtime/LitroLink.js';

// Shoelace is deliberately NOT imported.
//
// The recipe ships eight of its components here, but this site renders none of
// them: there is not one <sl-*> element in any page or component. They still
// cost every visitor about 120KB inside app.js, plus a render-blocking 19KB
// stylesheet in the document head (see src/route-meta.ts), plus 8.5MB of icon
// assets copied into the image.
//
// Add the component import and the theme link back together if a page ever
// wants one, and call setBasePath('/shoelace/') alongside it.

// Routes generated by the page scanner before each vite build.
import { routes } from './routes.generated.js';

document.addEventListener('DOMContentLoaded', () => {
  const outlet = document.querySelector('litro-outlet') as (Element & { routes: unknown }) | null;
  if (outlet) {
    outlet.routes = routes;
  } else {
    console.warn('[litro] <litro-outlet> not found — router will not start.');
  }
});
