#!/usr/bin/env bash
# Build a small throwaway git repo with real changes, for the demo recording.
set -euo pipefail
D="${1:?usage: seed-repo.sh DIR}"
rm -rf "$D"; mkdir -p "$D/src"; cd "$D"
git init -q .
cat > src/server.js <<'A'
const http = require("http");

function handler(req, res) {
  res.writeHead(200, { "Content-Type": "text/plain" });
  res.end("hello\n");
}

http.createServer(handler).listen(3000);
A
cat > src/util.py <<'A'
def slugify(text):
    return text.lower().replace(" ", "-")

def truncate(text, n):
    return text[:n]
A
mkdir -p docs
cat > README.md <<'A'
# demo

A tiny repo for the preen recording.
A
cat > docs/api.md <<'A'
# API

The server exposes one route.

| method | path | returns |
|--------|------|---------|
| `GET`  | `/*` | `{ "path": "<slug>" }` |

## Example

```bash
curl -s localhost:3000/Hello%20World | jq
```

```json
{ "path": "hello-world" }
```

> Slugs are generated by `slugify` in `src/util.py`.

See the [spec](https://example.com/spec) for the full contract.
A
cat > docs/design.md <<'A'
# Design notes

Three rules this service follows.

1. **One route.** Everything is a slug lookup.
2. **No state.** Restarting loses nothing.
3. **JSON only.** No HTML, no templates.

- [x] slugify handles punctuation
- [x] truncate adds an ellipsis
- [ ] rate limiting

## Why Python for the helpers

`re.sub` is short and the rules fit on one line:

```python
re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
```
A
git add -A
git -c user.name=demo -c user.email=demo@example.com commit -qm "initial"
cat > src/server.js <<'A'
const http = require("http");
const { slugify } = require("./util");

function handler(req, res) {
  res.writeHead(200, { "Content-Type": "application/json" });
  res.end(JSON.stringify({ path: slugify(req.url) }));
}

http.createServer(handler).listen(process.env.PORT || 3000);
A
cat > src/util.py <<'A'
import re

def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")

def truncate(text: str, n: int, suffix: str = "…") -> str:
    if len(text) <= n:
        return text
    return text[: n - len(suffix)] + suffix
A
cat >> README.md <<'A'

## Usage

Run `node src/server.js` and open <http://localhost:3000>.
A
