#!/usr/bin/env bash
# Build a small throwaway git repo with real changes, for the demo recordings.
#
#   ./demo/seed-repo.sh /tmp/preen-demo-repo
#
# It makes three things, all under DIR:
#   * a dirty working tree            -> preen diff, git diff | preen
#   * three git worktrees in .worktrees/ -> preen worktrees
#   * a bare sandbox in .pr/          -> preen pr (origin points at a public repo)
# .worktrees/ and .pr/ are git-ignored, so they never show up in preen diff.
set -euo pipefail
D="${1:?usage: seed-repo.sh DIR}"
rm -rf "$D"; mkdir -p "$D/src"; cd "$D"
D="$PWD"                                   # absolute, for git worktree add

# every commit below, with no dependency on the caller's git identity
g() { git -c user.name=demo -c user.email=demo@example.com "$@"; }

git init -q -b main .
cat > .gitignore <<'A'
.worktrees/
.pr/
A
cat > src/server.js <<'A'
const http = require("http");

function handler(req, res) {
  res.writeHead(200, { "Content-Type": "text/plain" });
  res.end("hello\n");
}

http.createServer(handler).listen(3000);
A
cat > src/util.py <<'A'
def slugify(text):
    return text.lower().replace(" ", "-")

def truncate(text, n):
    return text[:n]
A
mkdir -p docs
cat > README.md <<'A'
# demo

A tiny repo for the preen recording.
A
cat > docs/api.md <<'A'
# API

The server exposes one route.

| method | path | returns |
|--------|------|---------|
| `GET`  | `/*` | `{ "path": "<slug>" }` |

## Example

```bash
curl -s localhost:3000/Hello%20World | jq
```

```json
{ "path": "hello-world" }
```

> Slugs are generated by `slugify` in `src/util.py`.

## Errors

| status | when |
|--------|------|
| `400`  | the path is empty |
| `404`  | never: every path is a slug |
| `500`  | the slug helper raised |

Errors carry no body. The status line is the whole answer.

See the [spec](https://example.com/spec) for the full contract.
A
cat > docs/deploy.md <<'A'
# Deploy

One process, one port, no database.

```sh
PORT=8080 node src/server.js
```

## Health

There is no health route. If the port answers, the service is up.

## Rollback

Deploys are a git checkout and a restart, so a rollback is the same two
commands with an older tag.
A
cat > docs/faq.md <<'A'
# FAQ

**Why is there no router?** One route needs no router.

**Can I POST?** No. Every method is treated as `GET`.

**Where do slugs come from?** `slugify` in `src/util.py`, which lowercases,
replaces every run of non-alphanumerics with `-`, and trims the ends.
A
cat > docs/design.md <<'A'
# Design notes

Three rules this service follows.

1. **One route.** Everything is a slug lookup.
2. **No state.** Restarting loses nothing.
3. **JSON only.** No HTML, no templates.

- [x] slugify handles punctuation
- [x] truncate adds an ellipsis
- [ ] rate limiting

## Why Python for the helpers

`re.sub` is short and the rules fit on one line:

```python
re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
```
A
g add -A
g commit -qm "initial"

# ---- worktrees -------------------------------------------------------------
# Each one is what an agent would leave behind: a branch off main with a couple
# of commits on it. preen worktrees measures them against the merge-base, so
# they stay stable no matter what lands on main afterwards.
wt() { git worktree add -q -b "$2" "$D/.worktrees/$1" main; }

wt slug-unicode agent/slug-unicode
cd "$D/.worktrees/slug-unicode"
cat > src/util.py <<'A'
import re
import unicodedata

def slugify(text: str) -> str:
    text = unicodedata.normalize("NFKD", text)
    text = text.encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")

def truncate(text, n):
    return text[:n]
A
g commit -qam "slugify: fold accents before slugging"
cat >> docs/design.md <<'A'

## Unicode

Accented input is normalised to NFKD and stripped to ASCII before slugging,
so `Café` and `Cafe` land on the same slug.
A
g commit -qam "docs: note the unicode rule"

wt rate-limit agent/rate-limit
cd "$D/.worktrees/rate-limit"
cat > src/limiter.js <<'A'
const WINDOW_MS = 60_000;
const MAX = 120;
const hits = new Map();

function allow(key, now = Date.now()) {
  const seen = (hits.get(key) || []).filter((t) => now - t < WINDOW_MS);
  seen.push(now);
  hits.set(key, seen);
  return seen.length <= MAX;
}

module.exports = { allow, WINDOW_MS, MAX };
A
cat > src/server.js <<'A'
const http = require("http");
const { allow } = require("./limiter");

function handler(req, res) {
  if (!allow(req.socket.remoteAddress)) {
    res.writeHead(429, { "Retry-After": "60" });
    res.end("slow down\n");
    return;
  }
  res.writeHead(200, { "Content-Type": "text/plain" });
  res.end("hello\n");
}

http.createServer(handler).listen(3000);
A
g add -A
g commit -qm "add a fixed-window rate limiter"
cat >> docs/api.md <<'A'

## Limits

120 requests a minute per address. Over that the server answers `429` with a
`Retry-After` header.
A
g commit -qam "docs: write down the limit"
# left behind uncommitted, the way an agent that stopped mid-task leaves it
printf '\n- [ ] share the window across processes\n' >> docs/design.md
cat > NOTES.md <<'A'
# Notes

The window is per process. Behind more than one worker the real limit is
`MAX * workers`, which is not what the docs promise yet.
A

wt docs-polish agent/docs-polish
cd "$D/.worktrees/docs-polish"
cat > README.md <<'A'
# demo

A tiny repo for the preen recording.

## Run it

```sh
node src/server.js
curl -s localhost:3000/Hello%20World
```

## Layout

| path | what |
|---|---|
| `src/server.js` | the one route |
| `src/util.py`   | slug helpers |
| `docs/`         | api and design notes |
A
g commit -qam "README: how to run it, and what lives where"

# ---- pr sandbox ------------------------------------------------------------
# preen pr reads the PR over the API, so all it needs is a remote to resolve
# against. Nothing is cloned, fetched or checked out.
git init -q -b main "$D/.pr"
git -C "$D/.pr" remote add origin https://github.com/charmbracelet/vhs

# ---- the dirty working tree ------------------------------------------------
cd "$D"
cat > src/server.js <<'A'
const http = require("http");
const { slugify } = require("./util");

function handler(req, res) {
  res.writeHead(200, { "Content-Type": "application/json" });
  res.end(JSON.stringify({ path: slugify(req.url) }));
}

http.createServer(handler).listen(process.env.PORT || 3000);
A
cat > src/util.py <<'A'
import re

def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")

def truncate(text: str, n: int, suffix: str = "…") -> str:
    if len(text) <= n:
        return text
    return text[: n - len(suffix)] + suffix
A
cat >> README.md <<'A'

## Usage

Run `node src/server.js` and open <http://localhost:3000>.
A
